# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec jekyll build
      - run: sudo apt install rsync_3.1.3-6
      - run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" _site/ ubuntu@joejag.com:/home/ubuntu/sites/code.joejag.com
          
